import { SessionProvider } from "next-auth/react"
import StoreProvider from "../StoreProvider"
import SessionWrapper from "../SesionProvider"
import NavbarComponent from "@/components/navbar/navbar"
import FooterComponent from "@/components/footer/footer"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <SessionWrapper>
      <body>
      <StoreProvider>
      <header>
        <NavbarComponent/>
      </header>
      {children}
      <footer>
          <FooterComponent/>
      </footer>
      </StoreProvider>
      </body>
      </SessionWrapper>
    </html>
  )
}
