name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DOCKER_USERNAME # Replace with your actual environment name
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t $DOCKER_USERNAME/nextjs-app:${{ github.sha }} .
          docker push $DOCKER_USERNAME/nextjs-app:${{ github.sha }}
          docker tag $DOCKER_USERNAME/nextjs-app:${{ github.sha }} $DOCKER_USERNAME/nextjs-app:latest
          docker push $DOCKER_USERNAME/nextjs-app:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
