stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "Nextjs/nextjs-app"

# Build and push the Docker image
build_and_push_image:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - docker build -t "$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA" .
    - docker push "$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker tag "$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA" "$DOCKER_IMAGE:latest"
    - docker push "$DOCKER_IMAGE:latest"
  only:
    - main
